import React from "react";

const Menu = () => {
  const cafeCards = [
    {
      id: 1,
      img: "../../assets/image/Card1.jpg",
      name: "Espresso",
      aboutcafe: "Intense single shot of pure espresso.",
      price: 2,
    },
    {
      id: 2,
      img: "https://i.pinimg.com/736x/0e/63/9a/0e639a2520663ebda3d28630fad240e7.jpg",
      name: "Americano",
      aboutcafe: "Espresso diluted with hot water.",
      price: 2.5,
    },
    {
      id: 3,
      img: "https://picsum.photos/seed/coffee3/400/300",
      name: "Latte",
      aboutcafe: "Smooth espresso with steamed milk.",
      price: 3.5,
    },
    {
      id: 4,
      img: "https://picsum.photos/seed/coffee4/400/300",
      name: "Cappuccino",
      aboutcafe: "Equal parts espresso, steamed milk and foam.",
      price: 3.5,
    },
    {
      id: 5,
      img: "https://picsum.photos/seed/coffee5/400/300",
      name: "Flat White",
      aboutcafe: "Velvety microfoam over espresso.",
      price: 3.75,
    },
    {
      id: 6,
      img: "https://picsum.photos/seed/coffee6/400/300",
      name: "Mocha",
      aboutcafe: "Chocolate and espresso with steamed milk.",
      price: 4,
    },
    {
      id: 7,
      img: "https://picsum.photos/seed/coffee7/400/300",
      name: "Macchiato",
      aboutcafe: "Espresso 'marked' with a dash of foam.",
      price: 2.75,
    },
    {
      id: 8,
      img: "https://picsum.photos/seed/coffee8/400/300",
      name: "Iced Coffee",
      aboutcafe: "Chilled brewed coffee over ice.",
      price: 2.5,
    },
    {
      id: 9,
      img: "https://picsum.photos/seed/coffee9/400/300",
      name: "Iced Latte",
      aboutcafe: "Espresso and cold milk over ice.",
      price: 3.5,
    },
    {
      id: 10,
      img: "https://picsum.photos/seed/coffee10/400/300",
      name: "Cold Brew",
      aboutcafe: "Slow-steeped cold-brewed coffee.",
      price: 3.75,
    },
    {
      id: 11,
      img: "https://picsum.photos/seed/coffee11/400/300",
      name: "Affogato",
      aboutcafe: "Shot of espresso poured over ice cream.",
      price: 4.5,
    },
    {
      id: 12,
      img: "https://picsum.photos/seed/coffee12/400/300",
      name: "Turmeric Latte",
      aboutcafe: "Golden milk with warm spices.",
      price: 3.25,
    },
    {
      id: 13,
      img: "https://picsum.photos/seed/coffee13/400/300",
      name: "Chai Latte",
      aboutcafe: "Spiced tea blended with steamed milk.",
      price: 3,
    },
    {
      id: 14,
      img: "https://picsum.photos/seed/coffee14/400/300",
      name: "Matcha Latte",
      aboutcafe: "Ceremonial matcha whisked with milk.",
      price: 3.75,
    },
    {
      id: 15,
      img: "https://picsum.photos/seed/coffee15/400/300",
      name: "Hot Chocolate",
      aboutcafe: "Rich chocolate with steamed milk.",
      price: 3,
    },
    {
      id: 16,
      img: "https://picsum.photos/seed/coffee16/400/300",
      name: "Herbal Tea",
      aboutcafe: "Caffeine-free soothing herbal infusion.",
      price: 2,
    },
    {
      id: 17,
      img: "https://picsum.photos/seed/coffee17/400/300",
      name: "Tea (Black)",
      aboutcafe: "Classic black tea, brewed to order.",
      price: 1.75,
    },
    {
      id: 18,
      img: "https://picsum.photos/seed/coffee18/400/300",
      name: "Lemonade",
      aboutcafe: "Fresh-squeezed lemonade.",
      price: 2.25,
    },
    {
      id: 19,
      img: "https://picsum.photos/seed/coffee19/400/300",
      name: "Iced Tea",
      aboutcafe: "Refreshing iced tea, lightly sweetened.",
      price: 2,
    },
    {
      id: 20,
      img: "https://picsum.photos/seed/coffee20/400/300",
      name: "Frappe",
      aboutcafe: "Blended coffee with ice and cream.",
      price: 4,
    },
    {
      id: 21,
      img: "https://picsum.photos/seed/coffee21/400/300",
      name: "Croissant",
      aboutcafe: "Buttery, flaky croissant (pastry).",
      price: 2.5,
    },
    {
      id: 22,
      img: "https://picsum.photos/seed/coffee22/400/300",
      name: "Muffin",
      aboutcafe: "Fresh-baked muffin (various flavors).",
      price: 2.25,
    },
    {
      id: 23,
      img: "https://picsum.photos/seed/coffee23/400/300",
      name: "Bagel",
      aboutcafe: "Toasted bagel with optional spread.",
      price: 2,
    },
    {
      id: 24,
      img: "https://picsum.photos/seed/coffee24/400/300",
      name: "Panini",
      aboutcafe: "Grilled sandwich with melted cheese.",
      price: 4.5,
    },
    {
      id: 25,
      img: "https://picsum.photos/seed/coffee25/400/300",
      name: "Caesar Salad",
      aboutcafe: "Crisp romaine with Caesar dressing.",
      price: 5,
    },
    {
      id: 26,
      img: "https://picsum.photos/seed/coffee26/400/300",
      name: "Quiche",
      aboutcafe: "Savory egg tart with fillings.",
      price: 4.75,
    },
    {
      id: 27,
      img: "https://picsum.photos/seed/coffee27/400/300",
      name: "Smoothie",
      aboutcafe: "Fruit smoothie blended with yogurt.",
      price: 3.5,
    },
    {
      id: 28,
      img: "https://picsum.photos/seed/coffee28/400/300",
      name: "Yogurt Parfait",
      aboutcafe: "Layers of yogurt, granola, and fruit.",
      price: 3.25,
    },
    {
      id: 29,
      img: "https://picsum.photos/seed/coffee29/400/300",
      name: "Toast Avocado",
      aboutcafe: "Smashed avocado on toasted bread.",
      price: 3.75,
    },
    {
      id: 30,
      img: "https://picsum.photos/seed/coffee30/400/300",
      name: "Pancakes",
      aboutcafe: "Stack of pancakes with syrup.",
      price: 4.25,
    },
    {
      id: 31,
      img: "https://picsum.photos/seed/coffee31/400/300",
      name: "Breakfast Burrito",
      aboutcafe: "Eggs, cheese, and veggies wrapped.",
      price: 4.5,
    },
    {
      id: 32,
      img: "https://picsum.photos/seed/coffee32/400/300",
      name: "Scone",
      aboutcafe: "Buttery scone, plain or with fruit.",
      price: 2.5,
    }
  ];

  return <div>


  </div>;
};

export default Menu;
